#나중에는 빌드해서 도커파일 연결할건데, 아래는 우선 직접 작성

#services : 키워드
services:
    #db : 사용자정의
    mysqldb:
        # 아래는 키워드
        image: mysql
        restart: always
        volumes:
            #- mysql-compose-volume:/var/lib/mysql
            - ./data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root1234
            - MYSQL_DATABASE=rootdb
        ports:
            - "3306:3306"

#볼륨 만들고 연결
volumes:
    mysql-compose-volume:
